# Generated by Django 3.0.8 on 2020-08-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todolist',
            new_name='Produto',
        ),
    ]
